package br.com.squad3.aws.poc.model;

import br.com.squad3.aws.poc.enums.AddressType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
@Getter
@Setter
@Builder
@DynamoDBDocument
public class Address {

    @DynamoDBAttribute(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTypeConvertedEnum
    private AddressType addressType;

    private String postCode;

    private String address1;

    private String number;

    private String address2;

    private String neighborhood;

    private String city;

    private String state;
}
